#!/bin/sh
### BEGIN INIT INFO
# Provides:          stompserver_ng
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop the stompserver_ng gem
### END INIT INFO
#
NAME=stompserver_ng
DESC="stompserver_ng ruby gem"
#
NAMEHOME=/home/$NAME
#
CONFIGFILE="$NAMEHOME/$NAME.conf"
STOMPCMD="$NAMEHOME/bin/runserver.sh"
#
WORKDIR=$(grep "working_dir" $CONFIGFILE | cut -d" " -f2)
PIDFILE="$WORKDIR/$NAME.pid"
#
EXTRA_OPTS="--daemon --session-cache=25"
EXTRA_OPTS="${EXTRA_OPTS} ${STOMP_OPTS}"
#
set -e
# set -x
#
case "$1" in
    start)
        echo -n "Starting $DESC: "
        test -f /var/tmp/ruby-uuid && rm /var/tmp/ruby-uuid
        test -d $WORKDIR && rm -rf $WORKDIR
        su -l $NAME -c "$STOMPCMD"
        echo "$NAME."
        ;;
    stop)
        echo -n "Stopping $DESC: "
        pid=$(ps -ef | grep -i stompserver | grep -i ruby |awk '{print $2}')
        kill $pid
        echo "$NAME."
        ;;
    *)
        echo "Usage: $0 { start | stop }" >&2
        exit 1
        ;;
esac
#
# set +x
exit 0

